/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkSwitcher: typeof import('./../src/components/DarkSwitcher/index.vue')['default']
    DarkToggle: typeof import('./../src/components/DarkToggle/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    FullScreen: typeof import('./../src/components/FullScreen/index.vue')['default']
    FullScreenSwicther: typeof import('./../src/components/FullScreenSwicther/index.vue')['default']
    ICarbon3dCursor: typeof import('~icons/carbon/3d-cursor')['default']
    ICarbonCollapseCategories: typeof import('~icons/carbon/collapse-categories')['default']
    ICarbonTranslate: typeof import('~icons/carbon/translate')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpColdDrink: typeof import('~icons/ep/cold-drink')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    IMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    LocalePicker: typeof import('./../src/components/LocalePicker/index.vue')['default']
    PreferenceDrawer: typeof import('./../src/components/PreferenceDrawer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
